### ISSUE TITLE
Email to requestors who have not yet completed

### ISSUE THREAD

**Issue by lindak716** [psu-libraries/brs#10]

**Comment by lindak716** [comment]
@pah25
Pam -building an email sytsem into BRS is a significant add on.  What do you think about using an normal email distribution list and sending a reminder to the whole group - Thanks if you've done this -- If not - you have 2 days left!  - LK

**Comment by pah25** [comment]
Linda - That is what we have done in the past and if it isn't possible I am good with that.  I will continue to handle as I have in the past.

Thanks.

Pam
