### ISSUE TITLE
Updated Date column information under Active Requests does not appear correctly when updating

### ISSUE THREAD

**Issue by lindak716** [psu-libraries/brs#2]
In the attached example, I made an update to the cost center within BRS.  The date that I made the update is correct (8/25/17) but my user id is not KJR3.  The system appears to note the user id of the individual that submitted the original request...that is only a guess
[Budget_Request_Update_info_issue.pdf](https://github.com/psu-libraries/brs/files/2814303/Budget_Request_Update_info_issue.pdf)

**Comment by lindak716** [comment]
Allocated is an update, test for that

**Comment by cdmo** [comment]
Reviewed working for allocator and now working for requester dashboard report too. Ready for further review and testing.
