### ISSUE TITLE
Review trainng/documentation

### ISSUE THREAD

**Issue by lindak716** [psu-libraries/brs#21]
Printing and software section

**Comment by cdmo** [comment]
Pam is reviewing the videos and checking for update requirements. Pam will also update the glossary as needed.

**Comment by cdmo** [comment]
@pah25 also mentioned that they would come up with a "fiscal year prep checklist" kind of document listing all of the things that application administrators need to do before each new FY request period.

**Comment by lindak716** [comment]
Pam will review 1st video and will confirm if she wants the audio changed or not.
Possible to update audio on request form overview to account for new tab - software
No need to edit screen shots/video this year.

**Comment by pah25** [comment]
I reviewed the 1st video again and the audio does not need to be updated.  The script says the budget request system replaces ABLE as we begin in FT 2017/2018.

Thanks.

**Comment by cdmo** [comment]
Going to close this one then, please reopen if it needs to be open still.
