### ISSUE TITLE
PY Requests apply button doesn't do anything

### ISSUE THREAD

**Issue by cdmo** [psu-libraries/brs#23]
![Screenshot 2019-04-23 13 32 59](https://user-images.githubusercontent.com/523381/56602869-685a6880-65cc-11e9-965b-0de8a18ed45d.png)

from @dfreivalds

**Comment by pah25** [comment]
I asked Courtney to log in as a requester and pull up prior year request.  

Current functionality - choose prior year request from home screen
at drop down choose year that would like to review and then click on apply
the system then brings back a link to the prior year report that was requested.  Must click on the link to access the prior year report.
**Requesters can access prior year reports using this functionality.
