### ISSUE TITLE
Chrome printing operations column squished/break in words

### ISSUE THREAD

**Issue by cdmo** [psu-libraries/brs#24]
![Screenshot 2019-04-23 13 35 25](https://user-images.githubusercontent.com/523381/56602965-a8b9e680-65cc-11e9-9a7b-f839b1906620.png)

from @dfreivalds

**Comment by pah25** [comment]
I logged on to chrome and printed an allocation from test without exception

**Comment by cdmo** [comment]
Closing this one then. Feel free to reopen if it's not resolved. Also, feel free to close any issue that is marked "review" if you want.
