### ISSUE TITLE
Problem with dual roles

### ISSUE THREAD

**Issue by lindak716** [psu-libraries/brs#3]
Courtney Dillon is an Application Administrator and a Requestor. She submitted a request which went fine, but it didn't email the Allcocators that the request was complete. I edited the request and removed the "Complete" status, thinking she would them be able to edit the request.  However, the request does not show up in her "Active Requests", but show up under the "Cost Centers" section of the form. When she clicks on it to add a new one, she gets an error that states the request has already exists.

**Comment by cdmo** [comment]
Demoed for @pah25, and she approves. Next she (and Courtney) will test in QA.
