### ISSUE TITLE
Allocator and Budget Summary reports not correct (wrong fiscal year selected)

### ISSUE THREAD

**Issue by lindak716** [psu-libraries/brs#4]
Pam Hough emailed me that the Allocator Report wasn't right. It was showing allocations from 17/18, with no way to filter the results to 18/19.  I added the ability to filter the fiscal years and set the default to 18/19 on each report. I ended up setting the filter to default to 18/19 and added the relationship to the cost centers.  This made the reports fall into line and now they both match.

This is only a temporary fix for this year. All searches should default to the current fiscal year.

**Comment by cdmo** [comment]
Demoed for @pah25, and she approves. Next she will test in QA.

**Comment by cdmo** [comment]
This issue was tested back on March 22nd and approved. I am closing this issue. If we find in production that there is a problem with this feature we can re-open the issue.
