### ISSUE TITLE
Drop-down for allocators and the reports should sort by two character value as well

### ISSUE THREAD

**Issue by lindak716** [psu-libraries/brs#7]
As an allocator, all budgets/funds/cost centers are listed on the home screen.  The budgets currently do not appear in numeric order.  Would like the budget listing on home page to be in numeric order.

Current sort is budget number.  Should be budget number, then location code, then fund
For Example 06-070-70 AA 10010 should appear before 06-070-70 AN 10010
For Example Current sort 06-070-70 UP 10010, then 06-070-70 DS 10010, then 06-070-70 KP 10010

**Comment by cdmo** [comment]
Demoed for @pah25, and she approves of dropdown work. Need to change sort order for:

- [ ] Allocator homepage
- [ ] Allocator report page (not the dropdown)

**Comment by cdmo** [comment]
This is done and can now be reviewed by @pah25

**Comment by pah25** [comment]
can't close
