### ISSUE TITLE
Remember selection of budget area

### ISSUE THREAD

**Issue by lindak716** [psu-libraries/brs#8]
Because the number of active requests is so extensive, each time we are working through allocations we must search by budget and choose cost center for resulting list.  Once you allocate you must return to home and go through the search process again.  When allocating within same budget would like to perform search, allocate, and then hit back button to return to original search results.

A good solution for this is to have the selection be remmbered.

**Comment by cdmo** [comment]
Demoed for @pah25, and she approves. Next she will test in QA.
